package com.reinkyatto.webjens.remote.model.server

import com.reinkyatto.webjens.db.local.tables.serverlist.Server
import com.reinkyatto.webjens.utils.Const

data class ServerData(
    val bonus: String?,
    val database: String?,
    val free: String?,
    val game_code: String?,
    val game_donate: String?,
    val game_fps: String?,
    val game_id: String?,
    val game_location: String?,
    val game_max_port: String?,
    val game_max_slots: String?,
    val game_min_port: String?,
    val game_min_slots: String?,
    val game_mysql_free: String?,
    val game_name: String?,
    val game_private: String?,
    val game_status: String?,
    val game_tariff_testid: String?,
    val game_test_slots: String?,
    val game_tickrate: String?,
    val game_type: String?,
    val key_activate: String?,
    val location_aboutlocation: String?,
    val location_alert: String?,
    val location_cost: String?,
    val location_cpus: String?,
    val location_day_off: String?,
    val location_domain: String?,
    val location_fastdl_type: String?,
    val location_id: String?,
    val location_ip: String?,
    val location_ip2: String?,
    val location_locate: String?,
    val location_name: String?,
    val location_os: String?,
    val location_port_ftp: String?,
    val location_ram: String?,
    val location_ssh_port: String?,
    val location_status: String?,
    val location_type: String?,
    val monitoring_hide: String?,
    val monitoring_hostname: String?,
    val monitoring_password: String?,
    val monitoring_players: String?,
    val owner_user_id: String?,
    val partner: String?,
    val ranked_id: String?,
    val rate: String?,
    val server_add_memory: String?,
    val server_affinity: String?,
    val server_autopay: String?,
    val server_blist_url: String?,
    val server_cfg_writer: String?,
    val server_cpu_load: String?,
    val server_data: String?,
    val server_date_end: String?,
    val server_date_reg: String?,
    val server_fastdl: String?,
    val server_fps: String?,
    val server_free: String?,
    val server_ftp: String?,
    val server_gid: String?,
    val server_hdd: String?,
    val server_hdd_load: String?,
    val server_id: String?,
    val server_name: String?,
    val server_own_start: String?,
    val server_password: String?,
    val server_pid: String?,
    val server_port: String?,
    val server_ram_load: String?,
    val server_ramdisk: String?,
    val server_save_status: String?,
    val server_site: String?,
    val server_skype: String?,
    val server_slots: String?,
    val server_stats_url: String?,
    val server_status: String?,
    val server_steamworkshop: String?,
    val server_temp_install: String?,
    val server_tickrate: String?,
    val server_type: String?,
    val server_uid: String?,
    val server_version: String?,
    val server_vk: String?,
    val server_wakeup: String?,
    val tariff_id: String?,
    val transitions: String?,
    val user_access_level: String?,
    val user_activate: String?,
    val user_authenticator: String?,
    val user_balance: String?,
    val user_clanpay: String?,
    val user_contact_visible: String?,
    val user_date_reg: String?,
    val user_email: String?,
    val user_email_display: String?,
    val user_firstname: String?,
    val user_freeze_money_auction: String?,
    val user_id: String?,
    val user_last_date: String?,
    val user_lastname: String?,
    val user_new_email: Any?,
    val user_new_vk_id: Any?,
    val user_password: String?,
    val user_photo: String?,
    val user_restore_key: Any?,
    val user_skype: String?,
    val user_skype_display: String?,
    val user_status: String?,
    val user_stop_restore: String?,
    val user_sub_info: String?,
    val user_sub_news: String?,
    val user_tel_activate: String?,
    val user_tel_key: String?,
    val user_telegram: String?,
    val user_telephone: String?,
    val user_telephone_display: String?,
    val user_test_bd: String?,
    val user_test_web: String?,
    val user_ticketblock: String?,
    val user_token: String?,
    val user_vk_display: String?,
    val user_vk_id: String?
){

    fun toServerDBModel(): Server {
        return Server(
            id = server_id?:"",
            name = game_name?:"",
            game = getGame(game_name?:""),
            ip = location_ip?:"",
            port = server_port?:"",
            status = server_status?.toInt()?:-1
        )
    }

    private fun getGame(name: String): String = when {
        name.indexOf(Const.MINECRAFT) != -1 -> Const.MINECRAFT
        name.indexOf(Const.SAMP) != -1 -> Const.SAMP
        else -> ""
    }
}