package com.reinkyatto.webjens.remote.model.profile

import com.google.gson.annotations.SerializedName

data class UserData(
    @SerializedName("user_id") var userId: String?,
    @SerializedName("user_email") var userEmail: String?,
    @SerializedName("user_password") var userPassword: String?,
    @SerializedName("user_firstname") var userFirstname: String?,
    @SerializedName("user_lastname") var userLastname: String?,
    @SerializedName("user_status") var userStatus: String?,
    @SerializedName("user_balance") var userBalance: String?,
    @SerializedName("user_restore_key") var userRestoreKey: String?,
    @SerializedName("user_access_level") var userAccessLevel: String?,
    @SerializedName("user_date_reg") var userDateReg: String?,
    @SerializedName("free") var free: String?,
    @SerializedName("bonus") var bonus: String?,
    @SerializedName("partner") var partner: String?,
    @SerializedName("key_activate") var keyActivate: String?,
    @SerializedName("transitions") var transitions: String?,
    @SerializedName("rate") var rate: String?,
    @SerializedName("user_telephone") var userTelephone: String?,
    @SerializedName("user_skype") var userSkype: String?,
    @SerializedName("user_tel_activate") var userTelActivate: String?,
    @SerializedName("user_tel_key") var userTelKey: String?,
    @SerializedName("user_last_date") var userLastDate: String?,
    @SerializedName("user_freeze_money_auction") var userFreezeMoneyAuction: String?,
    @SerializedName("user_activate") var userActivate: String?,
    @SerializedName("user_ticketblock") var userTicketblock: String?,
    @SerializedName("user_telegram") var userTelegram: String?,
    @SerializedName("user_photo") var userPhoto: String?,
    @SerializedName("user_new_email") var userNewEmail: String?,
    @SerializedName("user_vk_id") var userVkId: String?,
    @SerializedName("user_new_vk_id") var userNewVkId: String?,
    @SerializedName("user_telephone_display") var userTelephoneDisplay: String?,
    @SerializedName("user_email_display") var userEmailDisplay: String?,
    @SerializedName("user_skype_display") var userSkypeDisplay: String?,
    @SerializedName("user_vk_display") var userVkDisplay: String?,
    @SerializedName("user_stop_restore") var userStopRestore: String?,
    @SerializedName("user_test_web") var userTestWeb: String?,
    @SerializedName("user_test_bd") var userTestBd: String?,
    @SerializedName("user_token") var userToken: String?,
    @SerializedName("user_sub_news") var userSubNews: String?,
    @SerializedName("user_sub_info") var userSubInfo: String?,
    @SerializedName("user_authenticator") var userAuthenticator: String?,
    @SerializedName("user_contact_visible") var userContactVisible: String?,
    @SerializedName("user_clanpay") var userClanpay: String?
)